function parser = pcomb_create_literal(literal)

literal_len = length(literal);

parser = @parse_literal;

    function result = parse_literal(input, position)
        tree = struct( ...
            'symbol', '', ...
            'type', 'terminal', ...
            'value', '' );
        is_match = lazy_eval(@strncmp, input, literal, literal_len);
        if is_match()
            tree.value = literal;
            result = struct( ...
                'success', true, ...
                'position', position + literal_len, ...
                'tree', tree );
        else
            result = struct( ...
                'success', false, ...
                'position', position, ...
                'tree', tree );
        end
    end

end
