function parser = pcomb_create_dot()

parser = @parse_dot;

    function result = parse_dot(input, position)
        tree = struct( ...
            'symbol', '', ...
            'type', 'terminal', ...
            'value', '' );
        if position <= length(input)
            tree.value = input(position);
            result = struct( ...
                'success', true, ...
                'position', position+1, ...
                'tree', tree );
        else
            result = struct( ...
                'success', false, ...
                'position', position, ...
                'tree', tree );
        end
    end

end
